/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface TuThienInterface extends Interface {
    getFunction(nameOrSignature: "MAX_PAGE_SIZE" | "campaignDescription" | "campaignName" | "donate" | "donorDonationCount" | "donorTotalAmount" | "emergencyWithdraw" | "getBalance" | "getDonation" | "getDonationCount" | "getDonations" | "getDonorCount" | "getDonorList" | "getSummary" | "getWithdrawal" | "getWithdrawalCount" | "getWithdrawals" | "isDonor" | "owner" | "renounceOwnership" | "totalDonated" | "totalWithdrawn" | "transferOwnership" | "updateCampaign" | "withdraw"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CampaignUpdated" | "Donated" | "OwnershipTransferred" | "Withdrawn"): EventFragment;

    encodeFunctionData(functionFragment: 'MAX_PAGE_SIZE', values?: undefined): string;
encodeFunctionData(functionFragment: 'campaignDescription', values?: undefined): string;
encodeFunctionData(functionFragment: 'campaignName', values?: undefined): string;
encodeFunctionData(functionFragment: 'donate', values: [string]): string;
encodeFunctionData(functionFragment: 'donorDonationCount', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'donorTotalAmount', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'emergencyWithdraw', values: [AddressLike, string]): string;
encodeFunctionData(functionFragment: 'getBalance', values?: undefined): string;
encodeFunctionData(functionFragment: 'getDonation', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getDonationCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getDonations', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getDonorCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getDonorList', values?: undefined): string;
encodeFunctionData(functionFragment: 'getSummary', values?: undefined): string;
encodeFunctionData(functionFragment: 'getWithdrawal', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getWithdrawalCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getWithdrawals', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'isDonor', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalDonated', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalWithdrawn', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateCampaign', values: [string, string]): string;
encodeFunctionData(functionFragment: 'withdraw', values: [AddressLike, BigNumberish, string]): string;

    decodeFunctionResult(functionFragment: 'MAX_PAGE_SIZE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'campaignDescription', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'campaignName', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'donate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'donorDonationCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'donorTotalAmount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'emergencyWithdraw', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDonation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDonationCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDonations', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDonorCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDonorList', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSummary', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getWithdrawal', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getWithdrawalCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getWithdrawals', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isDonor', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalDonated', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalWithdrawn', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateCampaign', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  
    export namespace CampaignUpdatedEvent {
      export type InputTuple = [name: string, description: string, timestamp: BigNumberish];
      export type OutputTuple = [name: string, description: string, timestamp: bigint];
      export interface OutputObject {name: string, description: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DonatedEvent {
      export type InputTuple = [donor: AddressLike, amount: BigNumberish, message: string, timestamp: BigNumberish];
      export type OutputTuple = [donor: string, amount: bigint, message: string, timestamp: bigint];
      export interface OutputObject {donor: string, amount: bigint, message: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawnEvent {
      export type InputTuple = [to: AddressLike, amount: BigNumberish, purpose: string, timestamp: BigNumberish];
      export type OutputTuple = [to: string, amount: bigint, purpose: string, timestamp: bigint];
      export interface OutputObject {to: string, amount: bigint, purpose: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface TuThien extends BaseContract {
    
    connect(runner?: ContractRunner | null): TuThien;
    waitForDeployment(): Promise<this>;

    interface: TuThienInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    MAX_PAGE_SIZE: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    campaignDescription: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    campaignName: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    donate: TypedContractMethod<
      [_message: string, ],
      [void],
      'payable'
    >
    

    
    donorDonationCount: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    donorTotalAmount: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    emergencyWithdraw: TypedContractMethod<
      [_to: AddressLike, _purpose: string, ],
      [void],
      'nonpayable'
    >
    

    
    getBalance: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getDonation: TypedContractMethod<
      [_index: BigNumberish, ],
      [[string, bigint, bigint, string] & {donor: string, amount: bigint, timestamp: bigint, message: string }],
      'view'
    >
    

    
    getDonationCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getDonations: TypedContractMethod<
      [_offset: BigNumberish, _limit: BigNumberish, ],
      [[string[], bigint[], bigint[], string[]] & {donors: string[], amounts: bigint[], timestamps: bigint[], messages: string[] }],
      'view'
    >
    

    
    getDonorCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getDonorList: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    getSummary: TypedContractMethod<
      [],
      [[bigint, bigint, bigint, bigint, bigint, bigint] & {balance: bigint, donated: bigint, withdrawn: bigint, donorCount: bigint, donationCount: bigint, withdrawalCount: bigint }],
      'view'
    >
    

    
    getWithdrawal: TypedContractMethod<
      [_index: BigNumberish, ],
      [[string, bigint, string, bigint] & {to: string, amount: bigint, purpose: string, timestamp: bigint }],
      'view'
    >
    

    
    getWithdrawalCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getWithdrawals: TypedContractMethod<
      [_offset: BigNumberish, _limit: BigNumberish, ],
      [[string[], bigint[], string[], bigint[]] & {recipients: string[], amounts: bigint[], purposes: string[], timestamps: bigint[] }],
      'view'
    >
    

    
    isDonor: TypedContractMethod<
      [_addr: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    totalDonated: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalWithdrawn: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateCampaign: TypedContractMethod<
      [_name: string, _description: string, ],
      [void],
      'nonpayable'
    >
    

    
    withdraw: TypedContractMethod<
      [_to: AddressLike, _amount: BigNumberish, _purpose: string, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'MAX_PAGE_SIZE'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'campaignDescription'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'campaignName'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'donate'): TypedContractMethod<
      [_message: string, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'donorDonationCount'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'donorTotalAmount'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'emergencyWithdraw'): TypedContractMethod<
      [_to: AddressLike, _purpose: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getBalance'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getDonation'): TypedContractMethod<
      [_index: BigNumberish, ],
      [[string, bigint, bigint, string] & {donor: string, amount: bigint, timestamp: bigint, message: string }],
      'view'
    >;
getFunction(nameOrSignature: 'getDonationCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getDonations'): TypedContractMethod<
      [_offset: BigNumberish, _limit: BigNumberish, ],
      [[string[], bigint[], bigint[], string[]] & {donors: string[], amounts: bigint[], timestamps: bigint[], messages: string[] }],
      'view'
    >;
getFunction(nameOrSignature: 'getDonorCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getDonorList'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getSummary'): TypedContractMethod<
      [],
      [[bigint, bigint, bigint, bigint, bigint, bigint] & {balance: bigint, donated: bigint, withdrawn: bigint, donorCount: bigint, donationCount: bigint, withdrawalCount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getWithdrawal'): TypedContractMethod<
      [_index: BigNumberish, ],
      [[string, bigint, string, bigint] & {to: string, amount: bigint, purpose: string, timestamp: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'getWithdrawalCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getWithdrawals'): TypedContractMethod<
      [_offset: BigNumberish, _limit: BigNumberish, ],
      [[string[], bigint[], string[], bigint[]] & {recipients: string[], amounts: bigint[], purposes: string[], timestamps: bigint[] }],
      'view'
    >;
getFunction(nameOrSignature: 'isDonor'): TypedContractMethod<
      [_addr: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalDonated'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalWithdrawn'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateCampaign'): TypedContractMethod<
      [_name: string, _description: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [_to: AddressLike, _amount: BigNumberish, _purpose: string, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'CampaignUpdated'): TypedContractEvent<CampaignUpdatedEvent.InputTuple, CampaignUpdatedEvent.OutputTuple, CampaignUpdatedEvent.OutputObject>;
getEvent(key: 'Donated'): TypedContractEvent<DonatedEvent.InputTuple, DonatedEvent.OutputTuple, DonatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'Withdrawn'): TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;

    filters: {
      
      'CampaignUpdated(string,string,uint256)': TypedContractEvent<CampaignUpdatedEvent.InputTuple, CampaignUpdatedEvent.OutputTuple, CampaignUpdatedEvent.OutputObject>;
      CampaignUpdated: TypedContractEvent<CampaignUpdatedEvent.InputTuple, CampaignUpdatedEvent.OutputTuple, CampaignUpdatedEvent.OutputObject>;
    

      'Donated(address,uint256,string,uint256)': TypedContractEvent<DonatedEvent.InputTuple, DonatedEvent.OutputTuple, DonatedEvent.OutputObject>;
      Donated: TypedContractEvent<DonatedEvent.InputTuple, DonatedEvent.OutputTuple, DonatedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'Withdrawn(address,uint256,string,uint256)': TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;
      Withdrawn: TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;
    
    };
  }