/**
 * Deploy TuThien lên local node và lưu contract address + ABI cho frontend
 */
import { network } from "hardhat";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const projectDir = path.resolve(__dirname, "..");

async function main() {
  const { ethers } = await network.connect();
  const [owner] = await ethers.getSigners();

  console.log("Deploying TuThien with owner:", owner.address);

  const tuThien = await ethers.deployContract("TuThien", [
    "Quỹ Từ Thiện Minh Bạch Blockchain",
    "Hệ thống quyên góp từ thiện minh bạch - Mọi giao dịch đều được ghi nhận vĩnh viễn trên Blockchain",
  ]);
  await tuThien.waitForDeployment();

  const address = tuThien.target;
  console.log("✅ TuThien deployed to:", address);

  // Lưu address + ABI cho frontend
  const artifactPath = path.join(projectDir, "artifacts/contracts/TuThien.sol/TuThien.json");
  const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));

  const frontendDir = path.join(projectDir, "frontend");
  if (!fs.existsSync(frontendDir)) fs.mkdirSync(frontendDir, { recursive: true });

  fs.writeFileSync(
    path.join(frontendDir, "contract.js"),
    `// Auto-generated by deploy-local.js\nexport const CONTRACT_ADDRESS = "${address}";\nexport const CONTRACT_ABI = ${JSON.stringify(artifact.abi, null, 2)};\n`
  );

  console.log("✅ Frontend config saved to frontend/contract.js");

  // Seed demo data
  const signers = await ethers.getSigners();
  const donor1 = signers[1];
  const donor2 = signers[2];

  await (await tuThien.connect(donor1).donate("Ủng hộ trẻ em vùng cao ❤️", { value: ethers.parseEther("2.0") })).wait();
  await (await tuThien.connect(donor2).donate("Chung tay vì cộng đồng 🤝", { value: ethers.parseEther("1.5") })).wait();
  await (await tuThien.connect(donor1).donate("Đợt 2 - Hỗ trợ bão lũ 🌊", { value: ethers.parseEther("0.5") })).wait();

  console.log("✅ Demo donations seeded (4 ETH total)");
}

main().then(() => process.exit(0)).catch((e) => { console.error(e); process.exit(1); });
